### ISSUE TITLE
Different versions between GitHub and Pypi.org

### ISSUE THREAD

**Issue by Maxime-POULAIN-Verlingue** [MAIF/melusine#125]
Hey !

I have tried to reinstall Melusine since I had the version 2.3.1 of october. 
I saw on GitHub that changes have been made on NLP tools (the Phraser object for example). 

First, I uninstalled melusine with : pip uninstall melusine.
When I did : pip install melusine. It downloaded melusine 2.3.2.
![image](https://user-images.githubusercontent.com/94903022/152164048-993f0e2e-a240-49f1-b614-5e58f274f05e.png)

However, when I tried to use the new version of the class Phraser, there was a mistake. The code downloaded with pip has still the old version of the file "phraser.py". So there are differences between the code of melusine in GitHub and the code we can download with pip. 

The ...\Lib\site-packages\melusine\nlp_tools\phraser.py that I have in my virtual env :
![image](https://user-images.githubusercontent.com/94903022/152165452-20f95853-6bf6-40ac-8c13-22b8b2719b3a.png)

The phraser.py file in GitHub :
![image](https://user-images.githubusercontent.com/94903022/152165878-fc80f4fc-1fc7-4a87-9ab9-edc8eec4c2e9.png)

Is it normal ? Am I the only one to have this problem ?

Thank you !

**Comment by TFA-MAIF** [comment]
Hello, 

Thank you for noticing.
Yes we are aware of the discrepencies. We are actually merging multiple contributions so we do it by iterations. 

Your previous contribution is also in line to be integrated. 
Sorry for the temporary discrepency. This will be fixed in a couple of weeks with a new release of Melusine. And we will give you details in the release note.

Best regards,
Tiphaine

**Comment by Maxime-POULAIN-Verlingue** [comment]
Okay, thank you for the quick reply ! 

I will try to download the last version from GitHub pending the new official release.

Have a good day !
